name: Auto Bump Dependencies

on:
  schedule:
    - cron: '0 4 * * *'  # Run every day at 04:00 UTC
  workflow_dispatch:

jobs:
  auto-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Bump dependencies
        run: |
          ncu -u
          npm install

      - name: Commit bumped deps
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore: bump dependencies"
        continue-on-error: true  # If no changes, this step is skipped

      - name: Run tests on bumped deps
        id: test
        run: npm run test
        continue-on-error: true

      - name: If tests pass, push to main
        if: steps.test.outcome == 'success'
        run: |
          git push origin HEAD:main

      - name: If tests fail, create PR
        if: steps.test.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bump-deps-failed
          title: "chore: bump dependencies (tests failed)"
          body: |
            Dependencies were updated but tests failed. Please investigate.
          commit-message: "chore: bump dependencies (tests failed)"

